---
name: Continuous Integration

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        python: [3.7, 3.8]
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
          pip install -r requirements.txt
          pip list
      - name: Pytest with coverage reporting
        run: pytest --cov=ipp --cov-report=xml
      - name: Upload coverage to Codecov
        if: matrix.python == 3.8 && matrix.os == 'ubuntu'
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
